### ISSUE TITLE
1 extracted music seems corrupted

### ISSUE THREAD

**Issue by gdommergue** [AdrienTD/wktools#3]
Hi Adrien, thank you for your amazing set of tools for WK!
After extracting all assets from the resource pack, all musics play nicely except this one (i'm using VLC to play audio):
BCP Extractor\bcpxtract\Warrior Kings Game Set\Sounds\Music\technology_endgame.mp2
I can barely hear some background noise when playing at high volume so the file seems to me "corrupted" but i don't know if it's corrupted from the original game or during the extraction with BCP Extractor...
Would you mind have a try on your side and see if you can reproduce?
Thanks!
The file i obtain after extraction: [technology_endgame.zip](https://github.com/AdrienTD/wktools/files/9692943/technology_endgame.zip)

**Comment by gdommergue** [comment]
Here's the same mp2 file with a speed x25 saved as mp3 160k using Audacity: [technology_endgame.zip](https://github.com/AdrienTD/wktools/files/9693004/technology_endgame.zip)
It sounds better :) but it's just a test to show you that this file is either corrupted from the beginning or it gets corrupted during the export.
If you have time and you manage to fix it, that's great, if not don't worry :)

**Comment by AdrienTD** [comment]
Oh yes, I know about that mp2 file. This is not an extraction bug, the file is actually like that.

In fact, the game does play that music, especially when you win some of the missions, and it is also corrupted there. It is hard to notice since the volume is very low, but if you listen closely you can hear it. If you wondered why some missions play a song when you complete it and others don't, that might be why.

You can notice the file is also very large in size compared to the other files. Now why the music got slowed down I have no idea, maybe it's some bug that happened when the developers tried to convert the music. Or maybe they did on purpose and wanted to hide it, who knows.

Hence, since the song is also played corrupted in-game, it is clearly a problem in the file itself, the extractor does correctly extract the file as it is.

**Comment by gdommergue** [comment]
I've also checked your code and didn't notice anything weird so you're definitively right 👍🏻
Thanks for your fast reply and appreciate your knowledge on this game!! 🥇
